config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "lists#index"
  resources :lists, only: %i[show create destroy update] do
    resources :bookmarks, only: %i[create destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :lists
  has_many :bookmarks
  validates :title, uniqueness: true
  validates :title, presence: true
  validates :overview, presence: true
  validates :overview, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render "lists/show", status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to lists_path(@bookmark), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
    @list = List.new
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
    @movie = Movie.all
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :index, status: :unprocessable_entity
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  def update
    @list = List.find(params[:id])
    @list.update(list_params)
    # No need for app/views/restaurants/update.html.erb
    redirect_to list_path(@list)
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-6 border-top bg-light">
    <div class="col-md-4 d-flex align-items-center">
      <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
        <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
      </a>
      <span class="mb-3 mb-md-0 text-muted">© <%= Time.now.strftime('%Y') %> MovieWatch</span>
    </div>
  </footer>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="/">
      🍿 MovieWatch
    </a>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieWatch</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "/layouts/navbar" %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render "/layouts/footer" %>
  </body>
</html>

app/views/lists/index.html.erb
<ul class="list-group my-3">
<% @lists.each do |list| %>
<li class="list-group-item position-relative">
<div class="row flex">
<div class="col-10">
<h4><strong><%= link_to list_path(list.id) do %><%= list.name %><% end %></strong></h4>
</div>
<div class="col-2">
<%= link_to list_path(list.id), class: "card-link btn btn-primary", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
  <i class="fa-regular fa-trash-can"></i>
<% end %>
  <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
      <i class="fa-regular fa-pen-to-square"></i>
  </button>
  </div>
</div>
</li>
<% end %>
</ul>

<hr />

<p>
  <a class="btn btn-primary" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
    Create a new list
  </a>
</p>
<div class="collapse" id="collapseExample">
  <div class="card card-body">

<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
            <%= simple_form_for @list do |f| %>
              <%= f.input :name %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <%= f.button :submit, class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<%= link_to "<< Back to lists", root_path, class: "btn btn-small" %>

<ul class="list-group my-3">
  <h2 class="list-group-item"><%= @list.name %></h2>
</ul>
<div class="row row-cols-1 row-cols-md-3 g-4">
      <% @list.bookmarks.each do |bookmark| %>
  <div class="col">
    <div class="card h-100" style="max-width: 20rem;">
        <%= image_tag bookmark.movie.poster_url, class: "card-img-top" %>
      <div class="card-body">
        <h5 class="card-title"><%= bookmark.movie.title %></h5>
        <p class="card-text"><%= bookmark.movie.overview %></p>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item"><%= bookmark.comment %></li>
      </ul>
      <div class="card-body">
          <%= link_to list_bookmark_path(bookmark.id), class: "card-link btn btn-primary", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
            <i class="fa-regular fa-trash-can"></i>
          <% end %>
      </div>
    </div>
  </div>
        <% end %>
</div>

<ul class="list-group my-3">
  <h2 class="list-group-item">
      <a class="btn btn-primary" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
    <strong>+</strong> Add a movie
  </a>
  </h2>
</ul>

<div class="collapse" id="collapseExample">
  <div class="card card-body">
    <%= simple_form_for [@list, @bookmark] do |f| %>
      <div class="container parent">
        <div class="row">
        <p>Select a movie:</p>
            <div class='col text-center'>
    <% @movie.each_with_index do |movie, i| %>
            <input type="radio" name="bookmark[movie_id]" id="img<%= i %>" class="d-none imgbgchk" value="<%= movie.id %>">
              <label for="img<%= i %>">
                <img src="<%= movie.poster_url %>" alt="<%= movie.title %>">
                <div class="tick_container">
                  <div class="tick">
                    <i class="fa fa-check"></i>
                  </div>
                </div>
              </label>
      <% end %>
            </div>
          </div>
        </div>
    <%= f.input :comment %>
    <%= f.submit "Add movie to list" %>
  <% end %>
  </div>
</div>